### ISSUE TITLE
Map literal with uneven number of forms

### ISSUE THREAD

**Issue by rap1ds** [borkdude/edamame#7]
**version** 0.0.3

**platform** OSX, Node.js, CLJS

**problem**

parse-string happily parses maps with uneven number of forms. I'd expect error to be thrown instead.

Is this a desired behaviour or a bug in the implementation?

If it's not a design choice but a bug, I'd happy to provide a PR to change this behavior. I guess the `dispatch` function should check that `parse-to-delimiter` returns even number of items before applying hash-map. https://github.com/borkdude/edamame/blob/945cb3ee22fc5d20445a2b007df318b0efa63205/src/edamame/impl/parser.cljc#L112

**repro**

```cljs
(edamame/parse-string "{:a :b :c}")
# => {:c nil, :a :b}
```

**expected behavior**

Same as cljs.reader:

```
(cljs.reader/read-string "{:a :b :c}")

# => Throws: Error: The map literal starting with :a contains 3 form(s). Map literals must contain an even number of forms.
```

**Comment by borkdude** [comment]
@rap1ds That actually goes back to this issue: https://github.com/borkdude/edamame/issues/4

**Comment by borkdude** [comment]
@rap1ds Thinking more about it, the approach suggested in #4 may not work, since then tools.reader completely takes over parsing and you won't get location information as metadata on the children nodes. So a PR would be most welcome, imitating everything that tools.reader does for maps: uneven number of children and duplicate keys.

**Comment by borkdude** [comment]
Also we should probably throw when reading a set with duplicate elements:

```
#{1 1}
```

Any more cases?
